// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'database/bean/qr_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 1021426411149740757),
      name: 'QrData',
      lastPropertyId: const IdUid(5, 7389084846791237988),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 6815115072972981733),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 878877963374874519),
            name: 'orgData',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 4683571720202739086),
            name: 'date',
            type: 10,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7389084846791237988),
            name: 'typeIndex',
            type: 6,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 1021426411149740757),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [8685187033509064897],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    QrData: EntityDefinition<QrData>(
        model: _entities[0],
        toOneRelations: (QrData object) => [],
        toManyRelations: (QrData object) => {},
        getId: (QrData object) => object.id,
        setId: (QrData object, int id) {
          object.id = id;
        },
        objectToFB: (QrData object, fb.Builder fbb) {
          final orgDataOffset = fbb.writeString(object.orgData);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, orgDataOffset);
          fbb.addInt64(3, object.date?.millisecondsSinceEpoch);
          fbb.addInt64(4, object.typeIndex);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final dateValue =
              const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 10);
          final object = QrData()
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..orgData = const fb.StringReader(asciiOptimization: true)
                .vTableGet(buffer, rootOffset, 6, '')
            ..date = dateValue == null
                ? null
                : DateTime.fromMillisecondsSinceEpoch(dateValue)
            ..typeIndex =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [QrData] entity fields to define ObjectBox queries.
class QrData_ {
  /// see [QrData.id]
  static final id = QueryIntegerProperty<QrData>(_entities[0].properties[0]);

  /// see [QrData.orgData]
  static final orgData =
      QueryStringProperty<QrData>(_entities[0].properties[1]);

  /// see [QrData.date]
  static final date = QueryIntegerProperty<QrData>(_entities[0].properties[2]);

  /// see [QrData.typeIndex]
  static final typeIndex =
      QueryIntegerProperty<QrData>(_entities[0].properties[3]);
}
